README.md, selectrum.el
=> Add option for showing count information before prompt.

CHANGELOG.md, selectrum.el
See also https://github.com/raxod502/selectrum/issues/4
=> Add history support

README.md
Amx now has support for selectrum, too.
=> Add amx to complementary extensions

selectrum.el
See discussion https://github.com/raxod502/selectrum/issues/49#issuecomment-616104369 about avoiding side effects for history selection.
=> Improve history selection

README.md
=> Extend section about complementary extensions

CHANGELOG.md, selectrum.el
=> Disable icomplete-mode automatically

CHANGELOG.md, selectrum.el
This aims to fix the problems discussed in #67.
=> [#67] Fix require-match behaviour

selectrum.el
See #130. 
@raxod502 
Unless it is an emergency I will always wait a few days before merging my PRs so you get a chance to comment if you want to.
=> [#130] Add user option for crm help in prompt

selectrum.el
=> Improve truncation indication for multiline candidates

selectrum.el
This prepares integration of Selectrum with [embark](https://github.com/oantolin/embark/) by adding some utility functions and also making `selectrum-active-p` a public variable.
=> Add and refactor minibuffer utility code

selectrum.el
The docstring wasn't up to date after #165.
=> Update docstring of selectrum--fix-minibuffer-message 

CHANGELOG.md
Missed the ref in #166, sorry.
=> Add missing reference in changelog

CHANGELOG.md, selectrum.el
=> Don't strip text properties of default

CHANGELOG.md, README.md, selectrum.el
=> Autoinsert separator for common values of crm-separator

CHANGELOG.md, selectrum.el
=> Don't add selectrum-insert-current-candidate insertions to history

CHANGELOG.md, README.md, selectrum.el
This really only makes a noticeable difference when there isn't text at the right margin, but I still find it helpful.
Should anything else be changed?
=> Create user option to highlight full candidate line.

CHANGELOG.md, README.md, selectrum.el
=> Choose candidates by display position

README.md
=> Add embark and browse-kill-ring to complementary extensions

selectrum.el
We don't need the input markers any more since candidates in minibuffer are displayed via an overlay now. There is no user visible change so there is no changelog. This will also fix the following case which wasn't working any more after #242:
```elisp
(minibuffer-with-setup-hook
(lambda () (insert "initial"))
(completing-read "Test: " '("initial input" "initial cand" "something else")))
```
=> Remove input markers

CHANGELOG.md, selectrum.el
Fix face isssues as described in #247, #236
=> Use faces of annotations and display properties

CHANGELOG.md, selectrum.el
Thanks @oantolin for reporting!
=> Fix return value of selectrum-completion-in-region

selectrum.el
=> Run annotation functions within minibuffer

CHANGELOG.md, selectrum.el
Display number of newlines as prefix for multi line candidates
=> Display multiline candidates with number of newlines prefix 

selectrum.el
This is for #267 which was introduced by recent refactorings.
=> Fix regression for completing file names

CHANGELOG.md, selectrum.el
=> Add affixation-function support

selectrum.el
Fix #279 which is a regression introduced by recent refactorings, the bug was not present in last release so no changelog.
=> Set file syntax table correctly

README.md
@minad I mentioned ivy-rich like suggested by @aspiers in #202 . Can you take a look?
=> Improve marginalia description

CHANGELOG.md, selectrum.el
See #286, allow for more complex affixation items and refactor annotation code.
=> Update annotation and affixation handling

CHANGELOG.md, selectrum.el
Attempt to improve the multiline prefix as discussed in #266
=> Improve multiline display

CHANGELOG.md, selectrum.el
=> Special case normalization of help--symbol-completion-table

CHANGELOG.md, selectrum.el
See #326, this is untested could you check with you test case @minad?
=> Preserve minibuffer-message-timeout

CHANGELOG.md, selectrum.el
=> Autoload selectrum-select-from-history

CHANGELOG.md, selectrum.el
=> Resort file completions only on directory change

CHANGELOG.md, selectrum.el
=> Disable current-line scrolling for auto-hscroll-mode

CHANGELOG.md, selectrum.el
=> selectrum-get-current-candidate: return prompt when selected

CHANGELOG.md, selectrum.el
=> Set minibuffer-default

CHANGELOG.md, README.md, selectrum.el
=> Improve selectrum-completion-in-region-styles

CHANGELOG.md, selectrum.el
=> Improve prompt selection in file completions where match is required

CHANGELOG.md, selectrum.el
Allow to insert the default when it is "selected".
=> Improve selectrum-insert-current-candidate

CHANGELOG.md, README.md, selectrum.el
As suggested by @minad and @oantolin, see #82.
=> Use completion-styles for default filtering and highlighting

CHANGELOG.md, selectrum.el
=> Improve behaviour for long prompts

CHANGELOG.md, selectrum.el
=> Only use scroll padding in mini windows

README.md
Newest version snails have fix byte compile warnings, please update information about Snails.
Thanks.
=> Adjust info about snails.

CHANGELOG.md, selectrum.el
@mathrick 
As per https://github.com/raxod502/selectrum/issues/82#issuecomment-763149870, I have worked on fixing the issues you had, could you give this some testing?
=> Improve tramp usage

CHANGELOG.md, README.md, selectrum.el
=> Remove selectrum-candidate-full property

CHANGELOG.md, selectrum.el
Follow up for #402 the initial selection of the prompt was missing
=> Improve default handling for file completions

selectrum.el
The selectrum--minibuffer-with-setup macro avoids issues with
:append and closures. See https://github.com/minad/consult/issues/193.
Thanks, @minad.
=> Use custom minibuffer-with-setup-hook implementation

CHANGELOG.md, selectrum.el
=> Auto extend highlighting with annotations

CHANGELOG.md, selectrum.el
=> Include line spacing when using fixed vertical window height

selectrum.el
=> Ensure face attribute is always specified

CHANGELOG.md, selectrum.el
=> Set `this-command` in `selectrum-repeat` to `selectrum-last-command`

CHANGELOG.md, selectrum.el
See #322, also improved selectrum-repeat so it can be used for repeating recursive sessions, too.
=> Rework state management

CHANGELOG.md, README.md, selectrum.el
=> Cleanup variable usage

CHANGELOG.md, README.md, selectrum.el
See https://github.com/raxod502/prescient.el/pull/97
=> Deprecate match highlighting faces

CHANGELOG.md, selectrum.el
=> Improve selectrum-completion-in-region for file name completions

CHANGELOG.md
Minor typographical improvement (in my estimation).
=> [#402] Use backticks rather than double quotes

selectrum.el
More improvements, getting rid of the unnecessary visual input variable for example.
=> Refactorings

selectrum.el
=> Refactor for style specific formatting

CHANGELOG.md, README.md, selectrum.el
=> Add quick keys

selectrum.el
We trade a little bit of `cons` allocations for faster sorting since we don't use the relatively slow `gethash` function in the sort comparison function. Unfortunately it adds a bit of complexity. But since this is performance critical I think it is worth it to use an optimized function here.
=> Optimize preprocessing

README.md
I am working a bit on the readme.
=> Readme: Better description for Orderless/Prescient

CHANGELOG.md, selectrum.el
=> Allow list of candidates for minibuffer-default

CHANGELOG.md, selectrum.el
=> Add support for different values of require-match argument

README.md
=> Update caveats section

CHANGELOG.md, selectrum.el
See #509, you need to `(setq selectrum-files-select-input-dirs t)` to configure it.
=> Add selectrum-files-select-input-dirs option

CHANGELOG.md, selectrum.el
=> Add selectrum-display-action-hook

selectrum.el
* Last backward compatible release providing selectrum-read is 3.1
* Next release will be 4.0
@clemera How do you feel about this - introducing the breaking point in the master branch soon? Or do you prefer to release another non-breaking 3.2 release first? Since the project seems to have gained more and more popularity recently it may make sense to make a clean cut now. This will give a bit more freedom with regards to adjusting internals. On the other hand, the deprecation notices we have in place are already a guide in the direction this project is going. Personally I would probably make the cut soon.
EDIT: There is one thing one should consider - if there are plans for more deprecations of public APIs we should add deprecation notices for these APIs and publish a 3.2. But this does …
=> Remove obsolete code

CHANGELOG.md
=> changelog: Update with regards to removed deprecations (#521)

CHANGELOG.md, selectrum.el
=> Ensure submitting a valid canidate is possible for dynamic tables

CHANGELOG.md, selectrum.el
=> Improve selectrum-completion-in-region-styles default

selectrum.el
See #526, bug wasn't present before #506 so no changelog.
=> Fix treating of default value lists

README.md
@clemera I added the vertico comparison to the readme. Is it a balanced/fair comparison? You may want to highlight more features of Selectrum? ~For example Selectrum enhances CRM, Vertico does not.~ (Edit: just added) Maybe also add that Selectrum is faster in certain scenarios?
=> README: Add comparison with Vertico

README.md
- Add more structure.
- Fix a few typos.
- Add some more of the customization options.
Try to make it easier to find information.
=> Re-organize info on customization in the README.
