raxod502/selectrum

- README.md
- selectrum.el
One thing I'm not sure is whether to do the `'selectrum-candidate-full` thing like in `selectrum-insert-current-candidate`. I think normally the user want to copy what he see, so copying the full path would be confusing. But on the other hand, now the suffix for directories won't be copied.
> add selectrum-kill-ring-save command to copy the current candidate

- README.md
- selectrum.el
Coming from ivy I missed the feature of being able to select the prompt. With this patch one can select the prompt instead of using `selectrum-submit-exact-input`. I haven't introduced a user option because I think there is nothing wrong with allowing this behavior by default. 
To test:
- Invoke  `find-file`
- Type some chars which match existing candidates
- Instead of accepting input with `C-j` you can now do `C-p RET`
This features frees the user of having to remember a keybinding for this action.
> Make prompt selectable

- selectrum.el
Here's an example:
```
(read-file-name "File: " "/home/" nil nil "name")
```
With `selectrum-mode` enabled, the minibuffer is:
```
1    File: /home/
kino/
```
With `selectrum-mode` disabled, it is:
```
File: /home/name
```
So their behavior is not consistent.
Selectrum actually selects a default candidate based on `initial` or `default-filename`. But when `mustmatch` is nil, the caller of `read-file-name` may want to save some file on disk, and it has a preferred file name that's not presented in the disk. This patch handles this situation.
The problem is: when the given `initial` or `default-filename` actually matches a candidate, it will still be in the user input, which is inconsistent with the behavior of `selectrum-read-file-name` in other situations. I've not find a simple way to …
> fix: in selectrum-read-file-name, handle initial/default-filename

- CHANGELOG.md
- selectrum.el
Submitting the empty prompt needs to return the empty string, currently when no default-candidate is given nil is returned which breaks some commands. This is also how default `completing-read` behaves.
> Don't possibly return `nil' in `selectrum-read'

- CHANGELOG.md
- README.md
- selectrum.el
See https://github.com/raxod502/selectrum/issues/14
The right margin text is displayed in the same line:
or in a new line, when the space is not enough:
> add: a text property for display string in the right margin

- selectrum.el
Inserting the full value on exit introduced a regression because `selectrum-candidate-selected-hook` currently gets always passed the full candidate but it needs the actual selected value.
> Run `selectrum-candidate-selected-hook` on exit

- CHANGELOG.md
- selectrum.el
Using `read-file-name-default` has many advantages because it takes care of any
additional minibuffer setup for file completion. Also any upstream changes for reading file names are automatically picked up.
Variables like `minibuffer-completing-file-name` are set automatically and you have additional features like using `M-n` to run file at point functions (which inserts the file path at point
into the minibuffer). Also `file-shadow-mode` and `tramp` work without additional changes.
> Use `read-file-name-default` for reading files

- CHANGELOG.md
- selectrum.el
I first thought about adding this to the `selectrum-candidate-inserted-hook` in my config and checking for `(eq this-command selectrum-insert-current-candidate)` but I think it might be generally useful to add those candidates to history. What do you think?
> Add inserted candidates to history

- selectrum.el
The candidates which should get added to history need to be inserted into the minibuffer. This PR also handles adding multi selections to history.
> Handle history on exit correctly (fixes #63)

- CHANGELOG.md
- README.md
- selectrum.el
This implements ideas mentioned in https://github.com/raxod502/selectrum/issues/42#issuecomment-614379709.
This is `selectrum-completion-in-region` on a backend created by me. I use the `:annotation-function` for the kind (variable, function, ...), which is displayed as the prefix; and I use the `:company-docsig` for the signature, which is displayed using right-margin text.
The `completion-at-point` function let binds `completion-extra-properties` to the extra props offered by backends, so we could just get the things we need from it.
- I use a italic face for those annotations, but I think it's better to also use some gray color to distinguish them from the candidate. Are you ok with me adding such face?
- Maybe we should also handle `:exit-function` (see the docstring of …
> [#42] Utilize annotation and docsig function in completion-in-region

- CHANGELOG.md
- selectrum.el
History again :sweat_smile: 
I removed the narrowing at some point because I though it's not necessary and did not remember why I added it. Just discovered it's needed because history saves the minibuffer contents when you start navigation history backwards and inserts it back when you navigate forward. So if you do `M-p` and then `M-n` your input is defined by the whole contents from before and when you afterwards type something nothing happens because this breaks everything.
> Fix history commands

- CHANGELOG.md
- selectrum.el
When doing `completion-in-region` and input a query and afterwards navigate through the list the `selectrum-current-candidate` highlighting sticks to the parts matched by the query for some reason. I have added a fix which cleans up the current candidate before executing the next command. I don't  understand why it only happens with `completion-in-region`.
> Fix highlighting for completion-in-region

- CHANGELOG.md
- selectrum.el
If `selectrum-num-candidates-displayed` is set to one the prompt gets highlighted instead of the candidate.
> Fix highlighting for one candidate display

- CHANGELOG.md
- README.md
- selectrum.el
Emacs already has the default faces `completions-annotations` and
`completions-common-part`, the latter of which we were already using
because we queried for completion candidates.
The former face we should inherit from instead of choosing our own color
for `selectrum-completion-annotation`. This increases the chances that
`selectrum-completion-in-region` will look as it should out-of-the-box,
as users' themes are more likely to have customized the built-in faces
than a new face.
We also add the face `selectrum-completion-docsig`, which inherits from
`selectrum-completion-annotation` and is italicized. Because we
distinguish between these two types of information, we provide our own
pair of faces for customization instead of making both use the single
built-in face …
> Inherit from built-in completions faces

- CHANGELOG.md
- selectrum.el
Don't show `.el` suffixes and don't insert whole path on `TAB` as reported by
[oantolin](https://www.reddit.com/user/oantolin) [here](https://www.reddit.com/r/emacs/comments/g6ocid/orderless_a_completion_style_that_matches/foegie3/), requoting below for easy reference:
(1) some of the candidates ended in .el and some did not (I'm used to none of
them ending in .el), but much more seriously,
(2) pressing TAB inserts the full path of the library, which, of course, is not
the argument find-library takes, so pressing TAB and then RET just produces an
error message rather than visiting the library file
I'm also working on a proposal of another PR for better implementation of `completing-read-multiple` addressing his IMO valid critique on current implementation.
> Improve selectrum-read-library-name

- selectrum.el
When the collection is a function, it can return "completion metadata". It can specify how to sort the candidates, which we should handle.
Simple test:
``` elisp
(defun my-collection (string pred flag)
(pcase flag
('metadata `(metadata (display-sort-function . ,#'identity)))
(t '("aaa" "aa" "a"))
(_ (error "FLAG is not handled"))))
(selectrum-completion-in-region (point) (point) #'my-collection nil)
```
With this patch, you'll see Selectrum puts "aaa" first, than "aa", than "a", which is expected. If you delete the `metadata` line in `my-collection`, Selectrum sorts the candidates based on their lengths, as it should.
The completion metadata has 4 keys:
- `category`: used for overriding `completion-styles` and `completion-cycle-threshold`, which is not relevant to us.
- …
> Utilize completion metadata and exit-function in completion-in-region-function

- CHANGELOG.md
- README.md
- selectrum.el
This PR implements an alternate replacement for `completing-read-multiple` which mimics the default interface more closely and makes it more convenient for selecting multiple candidates via completion. 
I requote [oantolins](https://www.reddit.com/r/emacs/comments/g6ocid/orderless_a_completion_style_that_matches/foegie3/) critique of the current behaviour here for easier reference:
- Selecting the first n-1 candidates with M-RET and then the last one with RET
feels a bit asymmetric. I think I instictively expected that I would select
all n candidates with M-RET and then RET would confirm the selection without
adding an extra (n+1)-st candidate.
- After pressing M-RET the contents of the minibuffer don't change. This has
positive and negative aspects:
- 1. On the positive side, the list of …
> Improve completing-read-multiple (also fixes #80)

- CHANGELOG.md
- selectrum.el
Simple test:
- `M-x shell`
- Type `cd /some/path`
- Call `completion-in-region`
- The path is expanded correctly. In previous versions, `/some/path` will be deleted.
@clemera offerd a lot of help and suggestions in https://github.com/raxod502/selectrum/pull/84 (Thanks!). I'd like to explain some of my decisions, and discuss on those I'm not sure about.
- @clemera suggested using `choose-completion-string`. It actually doesn't fix the bug. I looked into it, it uses `completion-boundaries` on `minibuffer-completion-table` and `minibuffer-completion-predicate`, but even I let bind those variables, it doesn't work. So I fixed it by directly using `completion-boundaries`.
Also, based on the code of `simple.el`, seems `choose-completion-string` is used when choose a candidate in the …
> Respect completion boundaries in completion-in-region

- CHANGELOG.md
- selectrum.el
I noticed this with comint input rings where empty strings are contained. In default completion UI empty strings are omitted, as well.
> Ignore empty strings

- selectrum-helm.el
Per the documentation for declare-function, files corresponding to
external packages should have "ext:" as prefix.
> Add "ext:" to declare-function invocations

- CHANGELOG.md
- selectrum.el
This will allow us to access the metadata for purposes as discussed in  #15 and #82 and allows other packages and commands to access those variables (see #94). With this patch we can retrieve the metadata like:
(completion-metadata input
minibuffer-completion-table
minibuffer-completion-predicate)
We could also decide to only pass the metadata instead (which would probably reduce garbage collection when exiting the minibuffer I guess). But the metadata can depend on the current input and the predicate passed to the completion table. Having metadata dependent on the input or predicate sounds like a crazy idea and I don't know if it actually happens in practice.
> Handle minibuffer completion table, predicate and metadata

- CHANGELOG.md
- selectrum.el
mouse-1 (left click) selects the candidate (like RET).
mouse-3 (right click) inserts the candidate (like TAB).
> Add the ability to interact with candidates via the mouse.

- CHANGELOG.md
- selectrum.el
This fixes #107. Emacs default completion functions return the string of a candidate without any text properties. I also removed `selectrum--result` because it is not needed anymore (it was there for the old implementation of `selectrum-completing-read-multiple`).
> [#107] Return chosen candidate without text properties

- CHANGELOG.md
- selectrum.el
This fixes #126. Instead of starting at the parent directory and sort the current directory to the top this approach selects the prompt initially which gives the same convenience but should avoid the problems with the old approach.
> [#126] Remove selectrum-read-directory-name

- CHANGELOG.md
- selectrum.el
Hello.
This is an attempt to fix #120. The current behavior has two problems:
1. An item in the list is pre-selected, instead of the default candidate.
2. One must go up to the prompt line to reveal the default candidate, meaning that the default is hidden by default.
I tried to address these in the following way:
1. When the default candidate is not in the list and there is no user input, pre-select the prompt line. That way, one can quickly hit `RET` to get the default, as expected.
2. When the default candidate is not in the list and there is no user input, always display the default candidate in the prompt line. That way, it is still clear what the default is when moving off of the prompt line.
One thing I was not able to figure out is how to make the default candidate display with …
> [#120] Try to improve behavior for when default candidate not in list.

- selectrum.el
After #122 the prompt gets highlighted for cases where it shouldn't:
To reproduce:
```elisp
(completing-read "Test: "
(list "test" "this")
nil nil nil nil  "this")
```
Type `te` in the prompt and you see that both the prompt **and** the current candidate are highlighted.
> Fix prompt highlight issue

- CHANGELOG.md
- selectrum.el
The insertion of additional candidates went wrong for non default `crm-seperator`.
> Fix candidate insertion for non default crm-separator

- README.md
- Mention `kill-whole-line`.
- Rephrase warning about killing the X server.
- Mention ignoring preceding input when completing file paths, since an example of navigating to the home directory was given.
> README.md: Small improvements to section Keybindings.

- CHANGELOG.md
- selectrum.el
As discussed previously (#116, #124) switching to overlays will solve a number of issues because Elisp code usually assumes that the  minibuffer only contains the current user input. 
I had to remove the code which handled display improvements for multi-line candidates. I currently don't know how to reimplement something similar for the overlay approach. Do you know of a way to check the visibility status within the overlay string?
Because of display issues I also had to change the way the mini window height got set which in effect sets the window height constantly so I removed the user option `selectrum-fix-minibuffer-height` for now. I prefer to have a constant height anyway but maybe it would be better to keep it? One could check the number of actual displayed candidates and resize the …
> Use overlay for candidates display and change multiline display

- selectrum.el
This lets the minibuffer grow dynamically until `selectrum-num-candidates-displayed` is reached. This restores the behaviour before #133 which introduced this new/wrong behaviour.
> [#149] Fix static minibuffer height for dynamic collections

- selectrum.el
This avoids an error in the case a match within the single lines of a multi line candidate can not be found.
> Fix no match case for multilines

- CHANGELOG.md
- selectrum.el
`add-to-history` errors when `minibuffer-history-variable` is `t` (which indicates history should be ignored). This meant  `selectrum-insert-current-candidate` would error when called from `selectrum-select-from-history`.
> Fix selectrum-insert-current-candidate error when history is ignored

- CHANGELOG.md
- selectrum.el
This fixes #90. Currently this doesn't try to use the opportunity to modify the candidates when `:may-modify-candidates` is set because I think usually the performance benefit should be small for dynamic collections.
> Avoid modifying candidates of dynamic collections

- CHANGELOG.md
- selectrum.el
This addresses #159 . The `read-buffer` predicate expects items to be a cons cell of the buffer name and the buffer object.
> Fix candidate format for read-buffer predicate

- CHANGELOG.md
- selectrum.el
This fixes the problems described in #157. In addition to that it takes care of sorting the default to top when it was passed as an absolute file name. Another problem this fixes (which I discovered while working on the others) is that the prompt should be selected if there are no candidates and a match isn't required (which wasn't done before so you wouldn't know you can actually submit the input).
> Fix prompt selection issues

- CHANGELOG.md
- selectrum.el
The `copy-seqence` doesn't complain when copying uncompiled lambdas but I noticed the bug when I got an error when passing a compiled one.
> Don't copy candidates function in selectrum-read

- selectrum.el
The cursor would jump forth and back when displaying the message. Overriding `make-overlay` isn't necessary any more because the content is only defined by the input now but instead we need to make sure the cursor stays at the front of the overlay by overriding `put-text-property` when calling `minibuffer-message`. I won't merge this before also adjusting `selectrum--fix-set-minibuffer-message` which I will do after upgrading to Emacs 27 where I can test it.
> Update handling of minibuffer message overlays

- CHANGELOG.md
- selectrum.el
This aims to fix #151 and #146. I also fixed the problem that each minibuffer invocation created a fresh overlay while we should better reuse the old one.
> Update minibuffer height according to text height

- CHANGELOG.md
- selectrum.el
When we switched to use an overlay for candidates display in #133 I forgot to update the code which handles the display of `selectrum-candidate-display-right-margin` so margins aren't currently displayed any more. This was after the last release so there is no changelog entry for this fix. But when fixing this I also used the opportunity to include the margins in the highlighting of the selected candidate because otherwise it's hard to see which candidate a margin string belongs to (which was my initial motivation for opening #83).
> Fix selectrum-candidate-display-right-margin

- selectrum.el
Currently we rebind `completing-read-function` in the next `selectrum-read` call but this is a bit cleaner because the handling can be moved into `selectrum-read-file-name` itself. The binding of `completing-read-function` gets now reset there to the previous value as soon as possible.
No user visible change so no changelog needed.
> Refactor completing-read-function rebinding for selectrum-read-file-name

- selectrum.el
Since I updated to the latest selectrum (#154), the height of the minibuffer
is sometimes incorrectly displayed. For example, if the INPUT is 'abc',
there will be two candidates. If you delete 'abc' and replace it with 'xyz'
which should be 20 more candidates, but the height of the minibuffer is
still only 3.
The following code seems to solve the problem.
> The minibuffer's hight not resize as the cands after #154, fixup it

- CHANGELOG.md
- selectrum.el
I think it makes sense to be able to customize these settings. These are the options made:
- selectrum-horizontal-whitespace-indicator: ".."
- selectrum-matching-line-indicator:         " -> "
- selectrum-newline-indicator:               "\\\\n"
- selectrum-truncated-candidate-indicator:   "..."
Should the faces applied to the strings also be customizable?
> Make truncation/replacement indicators customizable.

- selectrum.el
Usually the hook won't run when selectrum-active-p is nil but it is an extra guard and also make it easy to skip the hook entirely by `selectrum-set-selected-candidate` and other code which wants to stop automatic updates of selectrum.
> Add selectrum--skip-updates-p to allow skipping post-command-hook computations

- selectrum.el
After switching to Emacs 27 I noticed that `minibuffer-message` still has some problems. When you quit from a recursive session you see the message and the previous prompt but the display of candidates is delayed until after that. By delaying the execution of `minibuffer-message` one can jump straight to the previous session without delayed display of candidates. I additionally had to change the overlay priority like they do in `set-mininbuffer-message` so the overlay would display at the right place with the candidates overlay already present.
This problem wasn't present before we switched to using an overlay for candidates display so there is no changelog.
> Improve minibuffer-message

- CHANGELOG.md
- README.md
- selectrum.el
Create selectrum-minibuffer-map, replacing selectrum-minibuffer-bindings.
This addresses #71. Using a keymap allows for better working with
other packages (such as General and Use-Package) and better meets user
expectations.
> Use a keymap instead of an alist.

- selectrum.el
This addresses #187, the wrong behaviour wasn't present in the last release so there is no changelog.
> Fix behaviour of selectrum-fix-minibuffer-height

- CHANGELOG.md
- selectrum.el
We need to use ‘substitute-in-file-name’ prior to checking if the
minibuffer contents point to an existing file because we might have a
string such as “~/Documents//etc/hosts” in the minibuffer for which
‘file-exists-p’ will return nil but *is* in fact an existing file.
> Normalize path prior to checking if file exists

- CHANGELOG.md
- selectrum.el
Currently, an error occurs when TAB is pressed and no candidate
matches the minibuffer contents.  Moreover, the minibuffer contents
are erased.
This commit makes the behavior more lenient and similar to the default
minibuffer completion -- the bell is rung a “No match” message is
displayed.  Also, ‘completion-fail-discreetly’ is respected so none of
the aforementioned things are done if it is non-nil.
> Be more lenient when pressing TAB and nothing matches

- CHANGELOG.md
- selectrum.el
Const symbols don't need to be quoted, otherwise there will be a type mismatch in customization.
> Fix selectrum-count-style type mismatch

- README.md
Really small fix in the README; I was trying out selectrum this afternoon and got an error dropping the example config in my init: `global-set-key: Key sequence C - x SPC C - z starts with non-prefix key C`
Could also be spelled `(global-set-key "\C-x\C-z" #'selectrum-repeat)`
> Fix README's example binding selectrum-repeat

- CHANGELOG.md
- README.md
- selectrum.el
This purpose of this pull request is to make selectrum display indices only on visible candiates and to provide the user with a way to customize the character used for the indices of candidates.
To do this I created (as suggested by @okamsn in #194 ) an alist called `selectrum-quick-selet-keys` whose keys are indices and whose values are the characters that should be displayed for that index.
The name of the variable `selectrum-show-indices` was no longer well suited to its function, therefore I renamed it to  `selectrum-show-quick-select-keys`.
There are a few open questions however.
One is, should the alist use strings as values instead of characters?
Using characters works file for single letters. However, if the user prefers using numbers and has `selectrum-num-candidates-displayed` …
> Add selectrum quickselect keys.

- CHANGELOG.md
- selectrum.el
In case the function returned a list of strings we still possibly modified the returned results which can lead to surprises when the functions reuses them.
> Don't modify candidates returned by dynamic candidate function

- CHANGELOG.md
- selectrum.el
This will fix the recursive setting of `selectrum-should-sort-p` for `completion-in-region`. Also the function was written before selectrum supported handling certain metadata so I updated it to make use of the now existing handlers and also moved the handling of `:company-docsig` property into `selectrum--get-candidates-from-table` which is the appropriate place to handle this now.
While working on this I noticed that the annotations are all added at once to the whole collection, it might be faster to add them only on display for the displayed candidates. I will experiment and maybe provide another PR once this got merged.
> Refactor selectrum-completion-in-region

- CHANGELOG.md
- README.md
- selectrum.el
This adds the ability to configure a display action via `selectrum-display-action` to display candidates in a window outside the minibuffer as suggested in #227.
> Add display action to display candidates outside the minibuffer

- CHANGELOG.md
- README.md
- selectrum.el
When using `completing-read` sorting can be configured/disabled by providing `display-sort-function` via the metadata. To correctly disable sorting for `selectrum-read` one needs to set it in `minibuffer-setup-hook` like this:
```elisp
(minibuffer-with-setup-hook
(lambda ()
(setq-local selectrum-should-sort-p nil))
(selectrum-read "Switch to: " 
'("longest" "longer" "short")))
```
Before this PR this doesn't actually work because `selectrum--minibuffer-setup-hook` runs before the temporary hook added above. Alternatively we could use `(:append (lambda ...))` for `selectrum-read` but this might cause unexpected side effects for existing code which assumes `selectrum-read` runs early, we also have such code in selectrum itself (see `selectrum-read-file-name`). Because of that I moved the …
> Initialize selectrum after all other functions in minibuffer-setup-hook

- README.md
@raxod502 I added add consult link at a prominent place ~and modified the swiper section. The swiper section seemed a bit harsh to me. From my understanding after working on consult, I think such a swiper-like search is something which comes out naturally without doing much. It is obviously open for debate if that is a real search or isearch replacement. But it is nice to have options I think.~
> readme: add link to the consult and marginalia package

- CHANGELOG.md
- selectrum.el
Selectrums setup hook runs late now using `(:append...)`, see #242. This is a problem for use cases which assume the initial input is present from the start. Instead of handling it manually this PR passes the initial-input argument to `read-from-minibuffer` so the input is present from the start as it should be the case. For `selectrum-repeat` it is important to have exactly the same input as in the last session, this can be ensured by keep running it late and restoring the minibuffer content there so I left it in setup hook.
~~In addition to that I added support for the `initial-input` argument of `completing-read` which is deprecated but for backward compatibility  reasons I don't see how this could ever get removed. The comment noted that the initial-input argument does not work well …
> Select initial input when it equals the default

- CHANGELOG.md
- selectrum.el
Using `selectrum-candidate-display-suffix` overrides any annotations or usages of that property from the calling side so I switched to use an internal property for the special purpose of displaying the directory slashes. See #255.
> Use internal property for directory suffix

- CHANGELOG.md
- README.md
- selectrum.el
See #260. This will insert the path immediately if there is only one match and also ensures the syntax table is set correctly for all file completions. I also adjusted the exit-status to `sole` as this leads to the least surprising behaviour (no insertion of spaces after file completion which also does not happen with default completion). The exit status is very much tied to the way default completion works and `sole` seems to make the most sense with selectrum when it is not clearly `finished`. I also decided to push the mark at the start of the candidate so one can easily jump back to the beginning of the completion.
> Improve completion in region

- CHANGELOG.md
- selectrum.el
This does some refactorings, most notably removing internal usages of `selectrum-candidate-full` and the`selectrum--internal-candidate-display-suffix` property.
The initial purpose of this was to introduce completion boundaries, see #258. Maybe those can be added later but I wanted these refactorings to be included already.
> Refactoring

- CHANGELOG.md
- selectrum.el
This will ensure the refresh of the UI on candidate insertion. When the prompt was selected candidate insertion was a no-op, with this the selection switches to the first candidate. Refreshing the UI on candidate insertion with selected prompt is also needed if we ever add completion between path levels, see #258.
> Ensure refresh of UI on candidate insertion

- selectrum.el
Display the truncated multi lines of matched lines as annotation. This will overwrite any annotations the caller might have added but those wouldn't be visible for multi line candidate display anyway and using annotations for this makes more sense.
> Use annotations for multi line candidates display

- selectrum.el
This fixes another regression discovered with file completions due to recent refactorings. A good refactoring anyway because of DRY, see #267.
> Fix selectrum-submit-exact-input for file completions

- CHANGELOG.md
- selectrum.el
Add initial-input support for `completing-read`. Originated from #253.
> Support initial-input argument of completing-read

- selectrum.el
Due to recent changes file completions which have initially no candidates would trigger an error on exit.
> Fix error for empty file completions

- CHANGELOG.md
- selectrum.el
As reported by #286 there are affixation functions in Emacs 28 which mix list items with strings.
> Allow string elements for affixation items

- selectrum.el
I noticed the manual handling of different collection types isn't necessary because `all-completions` already handles everything for us.
> Refactor table normalization

- CHANGELOG.md
- selectrum.el
`selectrum-active-p` was recursively bound for all sessions which made it report the session state wrongly for recursive session where Selectrum wasn't active. As discussed elswhere at some point we should probably remove `selectrum--save-global-state` all together in favour of local variables.
> Bind selectrum-active-p locally

- CHANGELOG.md
- selectrum.el
> Handle default value symbols like completing-read-default

- selectrum.el
This removes selectrum--dynamic-candidates from `selectrum--save-global-state` as let binding it introduced problems with recursive minibuffers for dynamic completions, see #298 . I changed it to be set locally instead.
> Fix recursive sessions for dynamic completions

- README.md
@raxod502 @clemera This is a first try to make the readme a little bit less adversarial and such that it feels more objective. It probably needs a few more passes though, but this is a first step. Furthermore I reordered the supplementary packages since from my pov, I would recommend consult+embark instead of flimenu, amx and browse-kill-ring, but that's obviously my personal bias.
The section regarding the line number count of ivy vs selectrum should also be reworked again. If you only compare ivy and selectrum, it is 5000 vs 2000 loc (maybe after api deprecation, it will get better again ;). But if you look at the wider ecosystem, one  can compare for example ivy+counsel+swiper (13700) vs selectrum+consult (3500). Maybe it makes sense to remove the loc comparison and only emphasize that …
> Smoothen the readme

- CHANGELOG.md
- selectrum.el
This will address the problems with completing-read-multiple when submitting the prompt, see #285. Additionally I took care of submitting each individual candidate to `selectrum-candidate-selected-hook` and fixed `selectrum-insert-current-candidate` which didn't work correctly with completing-read-multiple when the prompt was selected.
> Improve completing-read-multiple

- CHANGELOG.md
- selectrum.el
The display action will be called from the window that selected the minibuffer but should use the value bound in the minibuffer for the case the caller has bound it locally for the current session.
> Allow locally set display actions

- CHANGELOG.md
- selectrum.el
As discussed in #75 and #312 `describe-variable` was slowed down with Selectrum because the predicate switches back to the last buffer for each candidate. By computing the candidates with the last buffer current by default we avoid the slow down for such cases. The docs don't mention any assumptions about the current buffer for the table/predicate, Ivy does run the computation before the minibuffer is even entered so it doesn't has this problem, we keep computing them late to allow for example `selectrum-set-selected-candidate` to skip the initial computation which is used by `embark` for example.
> Compute table candidates with last buffer current

- CHANGELOG.md
- selectrum.el
@minad As we discussed this lets you call `selectrum-exhibit` without updating the index which is allows for better handling of async completions as shown in #306.
> Add keep-selection arg to selectrum-exhibit

- CHANGELOG.md
- selectrum.el
`selectrum-extend-current-candidate-highlight`, `selectrum-show-indices`, `selectrum-right-margin-padding` and `selectrum-multiline-display-settings` wouldn't use the local session settings if there were any.
> Fix not applied local bindings for some user options

- CHANGELOG.md
- selectrum.el
This improves multiline display again by also showing the annotations when there is no input
> Show multiline annotations for empty input

- selectrum.el
The candidates should be saved with the same value they have in the collection.
> Pass candidate as it appears in collection to selectrum-candidate-inserted-hook

- CHANGELOG.md
- selectrum.el
`minibuffer-default` has been ignored before which this PR also fixes. This also adds an additional case for prompt selection when pulling a candidate with `M-n` (see #323).
> Allow setting default value via minibuffer-default

- CHANGELOG.md
- selectrum.el
Passing another table with the same metadata to `selectrum-completing-read` could trigger errors, see #315. By using `selectrum-read` directly and pass minibuffer-completion-table and predicate there is still access to the metadata and it avoids this problem.
> Improve selectrum-completion-in-region

- CHANGELOG.md
- README.md
- selectrum.el
The initial filtering styles for completion in region might generally differ from the styles you
want to use for usual completion and this option lets you configure that.
> Add selectrum-completion-in-region-styles

- CHANGELOG.md
- selectrum.el
See #334, the predicate caused unnecessary file access by the completion table which was noticeable on slow file systems. I assume this also helps with #210.
> Remove custom default predicate for file completions

- CHANGELOG.md
- selectrum.el
Set variables locally instead of let binding them so recursive sessions aren't affected.
> Improve selectrum-select-from-history

- CHANGELOG.md
- selectrum.el
Allow submitting selected prompt when it is a member of candidates and give feedback that match is required and submission not possible. This allowed submission in this case make sense and is also needed for #341 which will select the prompt for history commands.
> Improve exit when match required

- CHANGELOG.md
- selectrum.el
When browsing the history it makes sense to select the prompt because the history candidate might not be a member for the candidate set and also for file completions a history entry that is a directory would select the first file and not the history item.
> Select prompt for history commands

- CHANGELOG.md
- selectrum.el
It is better to keep the prompt unselected when a match is required for history commands, too. Currently deselection of the prompt after a history command would not always end up cleaning the prompt up and also for commands which use input history it makes no sense to have the prompt selected. Follow up to #341
> Improve prompt selection for history commands

- CHANGELOG.md
- selectrum.el
See #336, selectrum-get-current-candidate would throw an error when there are no candidates
> Fix selectrum-get-current-candidate

- CHANGELOG.md
- selectrum.el
The computation for the non candidates case needs to come first in order to avoid setting incorrect index, see #336.
> Always check available candidates before setting index

- CHANGELOG.md
- selectrum.el
Follow up for #352, turns out `read-from-minibuffer` does not set `minibuffer-default`.
> Use passed default if minibuffer-default unset

- CHANGELOG.md
- selectrum.el
This adds a variable to keep track of the buffer which entered the current session. This can also be used to fix the remaining problems with the slowdown of `describe-variable` in recursive sessions as discussed in #321.
> Speed up describe-variable for recursive sessions

- CHANGELOG.md
- selectrum.el
Don't trigger tramp automatically when using history commands. If one wants to trigger tramp for the current history item one can use `'selectrum-insert-current-candidate` to force a refresh.
> Improve history browsing with remote paths

- CHANGELOG.md
- selectrum.el
When using commands where the prompt would exceed the window width
the horizontal scroll wouldn't reset afterwards when a smaller
element was pulled into the prompt under certain conditions (for
example when using history commands), which has been fixed
> Ensure mini window resets scroll

- CHANGELOG.md
- selectrum.el
Reset minibuffer-history-postion when using `selectrum-insert-current-candidate` and for file browsing do not trigger a refresh when using history commands generally unless requested (maybe this behaviour could also be useful in general not only for file browsing?).
> Improve history usage in file completions

- CHANGELOG.md
- selectrum.el
It is better to check for `selectrum-insert-current-candidate` as `minibuffer-history-postion` is zero by default.
> Fix up #361

- selectrum.el
In case selectrum-insert-current-candidate is called indirectly make sure this-command is set correctly.
> Improve selectrum-insert-current-candidate

- CHANGELOG.md
- selectrum.el
Ensure the changes only affect the intended purpose and improve general behaviour:
- When navigating history the candidates should be shown again when returning to the start
- The history position should only reset when it was defined before
- There should be no refresh for `selectrum-insert-current-candidate` in general only when browsing through history
> Improve history browsing with file completions

- CHANGELOG.md
- selectrum.el
Check for tramp path and only prevent refresh for those, this way history behaviour is more consistent with other commands (where the candidate list updates when going through history) and a message can be shown for the particular case of a tramp path in history so one can manually trigger the refresh in that case.
> Improve file history browsing

- CHANGELOG.md
- selectrum.el
This has some bad side effects for editing with long prompts, see #345.
> Don't auto reset scroll

- CHANGELOG.md
- selectrum.el
Follow up for #376. Deactivate hscroll mode all together as its handled manually now. Also base scrolling points always on window width.
> Improve scrolling for long prompts

- CHANGELOG.md
- selectrum.el
Add scroll padding as prefix while preserving existing prefix and other properties (for single line candidates for multi line candidates they are discarded anyway).
> Add scroll padding as prefix

- CHANGELOG.md
- selectrum.el
When history position is non-zero and one does provide input it is expected the first match gets selected, also when using isearch for searching the history the currently matched prompt should be selected.
> Improve selection behaviour for history commands

- selectrum.el
This is how the minibuffer normally filters candidates.
It looks like the `partial-completion` doesn't work with Selectrum, but if some day that gets fixed, it would be useful to choose a special completion style for files. Another possible interesting case would be the `consult-location` category, where I personally would like to use a "semi-flex" style that basically replaces spaces by `.*?`
Now, with that said, I would like to embed a basic Emacs question here: isn't it a bit strange/inflexible that the minibuffer merges `completion-styles` with the styles stipulated in `completion-category-defauts/overrides` (cf. `completion--styles` function)? I think it be useful if the merging didn't happen when the appropriate `styles` entry of `completion-category-overrides` ends with nil.
> Honor completion-category-defaults and completion-category-overrides

- CHANGELOG.md
- selectrum.el
When typing a `$` right after a `/` provide env var completion like in default completion.
> Allow env var completion in file completions

- CHANGELOG.md
- selectrum.el
Follow up to #386, don't use cache for env completions, so when deleting the $ sign the files are shown again.
> Improve env var completion

- CHANGELOG.md
- selectrum.el
See #385, this tries to find matches via partial completion by default when the input directory doesn't exist. Used this way it isn't used as a completion-style but rather as a useful fallback to gather candidates which only triggers when it makes sense.
> Support partial-completion for files

- CHANGELOG.md
- selectrum.el
#390 introduced partial completions for the input path, afterwards one can continue to filter these using the configured filter function / completion-styles. In case one would like to use the partial-completion style on these results this still wouldn't work as reported by @mathrick in #82. To fix this I remapped the partial-style for the partial file completion case using `completion-styles-alist`. This isn't nice but seems like the best way to handle partial-completion style for files from Selectrum side.
> Improve partial-style file completions

- CHANGELOG.md
- selectrum.el
See #100, commands like completion-in-region should work out of the box regardless of the `enable-recursive-minibuffers` setting. Let binding it in this cases is also what the built-in `describe-...` commands do.
> Ensure enabled recursive minibuffers for special commands

- CHANGELOG.md
- selectrum.el
Don't use annotations to display multi line information so we don't possibly override any annotations provided and also allow to display multiline info for horizontal display. Display was updated to show a truncated version of the first line and afterwards the line count and all the matches within the multi line string.
> Adjust multi line display

- CHANGELOG.md
- selectrum.el
`selectrum-read-file-name` would error when passing a list for  `default-filename` as reported by @VojtechStep in #401 . Also we still had code which would remove the final slash for sorting the default first in file completions which wouldn't apply any more as dir candidates don't use an overlay any more to display the slash but contain it in their string now. 
I also improved the sorting so "/home/user/default" and "~/default" or a relative passed default get sorted first when they exist within the prompting directory. We still need to find a good way to indicate the default in file completions when that isn't the case, see #400.
> Improve default handling for file completions

- CHANGELOG.md
- selectrum.el
I don't know how I missed this one in #405.
Turns out that extracting the `~//ssh:host:` prefix out of `~//ssh:host:do` is
surprisingly tricky. Luckily `completion--sifn-requote` does basically just
that.
> Fix file-name completion after ~//ssh:host:do

- CHANGELOG.md
- selectrum.el
The height wouldn't correctly update in some cases if `window-resize-pixelwise` wasn't set during `selectrum--update-minibuffer-height`, see #303.
> Ensure pixelwise resize for minibuffer height update

- CHANGELOG.md
- selectrum.el
Include a virtual candidate when the passed default path doesn't exists or lies outside the prompting directory, see #400 and #420:
```elisp     
;; No default
(read-file-name "Check: " "~/")
;; Not existing default within prompt dir
(read-file-name "Check: " "~/" "~/foo")
;; Not existing default outside prompt dir
(read-file-name "Check: " "~/" "/foo/foo")
;; Existing default within prompt dir
(read-file-name "Check: " "~/" "~/.emacs.d/")
;; Existing defaults outside prompt dir
(read-file-name "Check: " "~/" "~/.emacs.d/elpa/")
(read-file-name "Check: " "~/" "~/.emacs.d/init.el")
```
> Allow virtual candidate for file prompts

- CHANGELOG.md
- selectrum.el
Prepend the background for selection highlight to ensure selection is always visible, see #425
> Improve selection highlight for candidates with background property

- CHANGELOG.md
- selectrum.el
If the theme uses backgrounds to highlight matches they wouldn't be visible on the selection.The popular zenburn and modus themes both do this so it seems safer not going that route for now until there is abetter fix for #425
> Undo prepend of background for selection

- CHANGELOG.md
- selectrum.el
* This variable allows the user to customize the format
of the default value indicator
* The variable can also be nil in order to hide the indicator
* Do not remove the properties from the candidate string,
for example Consult uses candidate strings with the invisible
property
* See also #444
> Add selectrum-default-value-format customizable variable

- CHANGELOG.md
- README.md
- selectrum-helm.el
- selectrum.el
This is only a first step towards #443. Please tell me if we should proceed with this, @clemera. I searched through github and found at least two packages (maybe not yet published), which started to use the `selectrum-read` API.
* https://github.com/stardiviner/kiwix.el
* https://github.com/landakram/org-z/blob/master/org-z-selectrum.el
So I think it is better to do this rather sooner than later, since the situation will get only more problematic the more popular selectrum becomes. Otherwise we just end up with many selectrum-xyz packages, similar to all the ivy-xyz and helm-xyz packages.
The question is which of the packages really need the dynamic candidate function functionality. The packages which really need the dynamic candidate function could instead use the async functionality of …
> Private api

- selectrum.el
The variable should not always be overwritten since it may be configured from outside via a minibuffer-setup-hook.
I believe this bug has been introduced in #441. It broke the consult selectrum integration. The no-move-default-candidate option can be safely removed later on since it is nowhere used.
> Do not overwrite selectrum-move-default-candidate

- selectrum.el
Seems to work for me. See #451. I also removed the redundant selectrum-is-active.
> Disable mouse tooltips in Selectrum buffer

- selectrum.el
This isn't an actual, named, widget type defined using
`define-widget', but a variable that holds an ad hoc widget
composition.  This means that only the value is of any use;
the symbol name is meaningless to the widget abstraction.
> Use completion--styles-type as intended

- CHANGELOG.md
- selectrum.el
See #419 
@minad I did it a bit differently since in Selectrum we filter the collection only initially with a different style and I would like to keep that behavior. You might want to update the consult version for `completion--cycle-threshold` as this also checks for possibly defined threshold by metadata.
> Support cycling for in completion in region

- CHANGELOG.md
- selectrum.el
When hitting the return key on a candidate while existing candidates have been selected already, I get `(wrong-type-argument char-or-string-p nil)`.
I figured out it's because `selectrum--previous-input-string` is a buffer-local variable, which I think makes it `nil` later on inside `with-temp-buffer` which is used to clean up the candidate list and append on the selected one.
I'm pretty new to emacs and elisp in general, so while this fix works for me, maybe you can suggest a better one?
> Fix nil selectrum--previous-input-string in CRM

- CHANGELOG.md
- selectrum.el
Corresponding PR for #458. I implemented the `group-function`. You may want to pull the first four simplification commits directly. In order to test the grouping feature, you can `eval-buffer` consult.el from https://github.com/minad/consult/pull/234.
consult-mode-command:
> Group function

- .circleci/config.yml
- CHANGELOG.md
- README.md
- selectrum-helm.el
- selectrum.el
Emacs 26 is usually the minimal version in use and this will free us from adapting the development for the older versions see #454.
> Drop Emacs 25 support

- selectrum.el
I tried to read the `selectrum--update` function and it is really long. I extracted a few parts to separate functions. This reduces indentation and helps to build a better mental picture of what is going on. I hope that some of the long functions can be split up even more. I see `selectrum--update` as a sequence of relatively separate operations: compute new candidates, compute display string, resize window and so on. Ideally the code would reflect that. As a first step, can we please merge this as courtesy to the reader?
> Refactorings

- selectrum.el
After #476, I was wondering when the grouping should actually be performed.
I made a small experiment: One thing I always found annoying about the Orderless style matching, is that prefix matching strings are not preferred. Usually I start to type some prefix and then refine with the following tokens. The code here is just an experiment not ready to be merged, since it contains Consult/Orderless-specific hacks.
It may still be interesting to discuss this:
* Should such a reordering rather be done on the level of the completion style to allow more general usage? Or is it a hard rule that completion styles only filter and do not perform any kind of reordering?
* In Selectrum we may want to reconsider where we actually do the grouping. Currently we do the grouping after the initial sorting, …
> Perform grouping after refinement, allow reordering during refinement

- selectrum.el
@clemera I reworked this now. I went with a simple solution - it is all not that bad. We format the candidate strings and return `(candidate . group)` pairs. We can generalize this more when we actually need it, for example when we want `(candidate group prefix suffix)`. Instead of `horizp` we have `should-annotate` now and we only call the annotation functions when really needed.
> Rework display

- CHANGELOG.md
See #450, has been fixed during recent refactorings.
> Fix arrow in fringe for annotated candidates

- README.md
I received a personal email the other week pointing out that [the Icicles section in the README](https://github.com/raxod502/selectrum/tree/21cee863a07f9114172d5b9bd33eeed7f11bcf66#icicles) does not address the features of Icicles in comparison to those of Selectrum, and that the tone reads as disrespectful.
This pull request updates that section of the README to make it clear that distribution by EmacsWiki is a serious problem, but that this does not have bearing on the functionality of Icicles.
If anyone else has revisions they would like to make such that this section, or others, of the README are more polite, then please by all means make them. I am not the most skilled at this.
> Elaborate on Icicles section in README

- CHANGELOG.md
- selectrum.el
For crm the UI interaction is smoother when selecting the input after
insertion, see https://github.com/oantolin/embark/issues/183
> Select input after crm candidate insertion

- CHANGELOG.md
- selectrum.el
When all candidates were selected in a completing-read-multiple session the return value wasn't correct, which has been fixed.
> selectrum--exit-with: Fix no remaining candidate case for crm

- CHANGELOG.md
- README.md
- selectrum.el
See #498 where an error was discovered by @mohkale [here](https://github.com/raxod502/selectrum/issues/498#issuecomment-803368243):
> backward-kill-sexp works well enough but when my current path is ~/ or even just {~/} or / I get a kill-region: Text is read-only: #<buffer *Minibuf-1*> which makes me think it's trying to delete the prompt?
> Add selectrum-backward-kill-sexp command

- CHANGELOG.md
- README.md
- selectrum.el
As recently discussed on reddit, icomplete/default completion [sorts by history](https://www.reddit.com/r/emacs/comments/m9avdn/orderless_selectrum_prescient_and_consult_basic/grniolf?utm_source=share&utm_medium=web2x&context=3). I propose we do the same in the default Selectrum sorting function for consistency. And it is also kind of nice since this gives some kind of cheap emulation of prescient sorting, arguably without the more sophisticated frecency calculation.
> selectrum-default-candidates-preprocess-function: Sort by history

- CHANGELOG.md
- selectrum.el
* When passing a cons as INITIAL-INPUT argument to `completing-read`
the point was off by one, which has been fixed ([#528], [#530]).
> Fix initial-input position

- test/install.el
I'm not sure this is more widely needed, or the best approach, but this is to get around the issue that if one is using the test scripts, and has the tmp directory hanging around for awhile, the packages can get out of date.
> add message for emacs-dir for test scripts

- CHANGELOG.md
- selectrum.el
There is no reason to provide this function on top of
selectrum-is-active and minibuffer-contents.
> Deprecate selectrum-get-current-input

- README.md
Prescient has improved a bit since Selectrum was created, and I think it's worth describing it in a bit more detail.  It might also be worth describing Orderless in more detail too, but I don't know as much about that package.
- Add link to Prescient README in this section.
- Note that other filtering styles are available and that more can be added by users.
- Mention being able to toggle some of the filtering features on the
fly, such as case/character folding or which filtering methods are
active.
- Mention being able to list fully matched candidates before partially
matched candidates.
- Note that sub-queries can match in any order, but that all queries
must match.
- Note that multiple parts of a candidate can be highlighted.
- Tentatively remove warning about "optimality" of …
> Add to description of Prescient in README.

- CHANGELOG.md
- selectrum.el
Instead of deleting all instances of an element before moving it to
the front, move all instances to the front.  This is important for
candidates that differ by text properties.
> Fix `selectrum--move-to-front-destructive`.

- CHANGELOG.md
- selectrum.el
- Use `find-library-source-path` in Emacs versions starting with 28.1.
The variable `find-function-source-path` was renamed to
`find-library-source-path` starting with Emacs 28.1.
- Always use a text property in `selectrum-read-library-name`.
This fixes #577.  If the user chooses a matching candidate with
`selectrum-submit-exact-input`, then the returned candidate won't
have the needed property.  In that case, we select the first item in
the propertized candidate list that is `equal` to the selected
candidate.
- Update changelog.
> Fix `selectrum-read-library-name`.

- CHANGELOG.md
- selectrum.el
These two remappings are not needed any more, since the keymap
inherits from minibuffer-local-map and they get in the way of
minibuffer-keyboard-quit's new functionality in Emacs 28.
> Don't remap keyboard-quit in selectrum's keymap

- selectrum.el
Hi Radon,
This fixes a byte-compiler warning when installing selectrum with `package.el`:
```
Compiling file /home/skangas/.emacs.d/package-quickstart.el at Mon Jan 10 05:33:47 2022
package-quickstart.el:2060:2170: Warning: defcustom for ‘selectrum-mode’ fails
to specify containing group
```
See previous discussion on the Emacs bug tracker here:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53153#14
Thanks!
> Add :group parameter to selectrum-mode

- CHANGELOG.md
- selectrum.el
- This makes matching candidates easier, depending on what completion
styles are used.  For example, if the `substring` completion style
is not used.
- This is already done for completing file paths in region,
but now is also true for other candidates.
- This useful behavior is also done by `consult-completion-in-region`.
See #576.
> Include prefix input in `selectrum-completion-in-region`.

- CHANGELOG.md
- selectrum.el
Fixes #585.  Trying to click on candidates in a buffer displayed via
`selectrum-display-action` would select that window, which would make
Selectrum inactive.
This simply reselects the minibuffer window in a local `pre-command-hook`. I
don't think that this would cause any problems, but am not very
familiar with this feature. There might be a better way of doing this.
This seems to work with posframe and normal windows, but I'm not sure how well it works with other ways of displaying buffers.
> Select the minibuffer before running commands in a displayed Selectrum buffer.

- CHANGELOG.md
- selectrum.el
Previously, the buffer would only be created if there were candidates
to display.  This would then cause errors for empty directories, and
wouldn't allow us to insert candidates when moving out of the empty
directory.
Fixes #571.
> Make sure Selectrum display buffer always exists before use.

- CHANGELOG.md
- README.md
- selectrum.el
- Add option `selectrum-cycle-movement`.  When enabled, navigation
commands wrap around.  Requested in #570.
- Add commands to navigate by groups (with optional cycling).
Requested in #554.
> Add commands to navigate by groups.  Add cycling to commands.

- README.md
- selectrum.el
- In the documentation string of the user option
`selectrum-extend-current-candidate-highlight`
- In the documentation string of the face
`selectrum-current-candidate`
- In README.md
> Mention the `:extend` face attribute for Emacs 27+.
